/* Database schema to keep the structure of entire database. */
CREATE TABLE IF NOT EXISTS patients (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL,
    date_of_birth DATE,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS medical_histories (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    admited_at TIMESTAMP,
    patient_id INT,
    status VARCHAR(100),
    PRIMARY KEY(id),
    CONSTRAINT fk_patient FOREIGN KEY (patient_id) REFERENCES patients(id)
);

CREATE TABLE IF NOT EXISTS treatments (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    type VARCHAR(100),
    name VARCHAR(100),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS treatments_medical_histories(
    medical_history_id INT NOT NULL,
    treatment_id INT NOT NULL,
    CONSTRAINT fk_medical_history FOREIGN KEY (medical_history_id) REFERENCES medical_histories(id),
    CONSTRAINT fk_treatments FOREIGN KEY (treatment_id) REFERENCES treatments(id)
);

CREATE TABLE IF NOT EXISTS invoices (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    total_amount DECIMAL,
    generated_at TIMESTAMP,
    paid_at TIMESTAMP,
    medical_history_id INT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_medical_history FOREIGN KEY (medical_history_id) REFERENCES medical_histories(id)
);

CREATE TABLE IF NOT EXISTS invoice_items(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    unit_price DECIMAL,
    quantity INT,
    total_price DECIMAL,
    invoice_id INT NOT NULL,
    treatment_id INT NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT fk_treatments FOREIGN KEY (treatment_id) REFERENCES treatments(id),
    CONSTRAINT fk_invoices FOREIGN KEY (invoice_id) REFERENCES invoices(id)
);

CREATE INDEX fk_patient_index ON medical_histories (patient_id ASC);
CREATE INDEX fk_medical_history_index ON treatments_medical_histories (medical_history_id ASC);
CREATE INDEX fk_treatment_index ON treatments_medical_histories (treatment_id ASC);
CREATE INDEX fk_treatment_invoice_index ON invoice_items (treatment_id ASC);
CREATE INDEX fk_medical_history_invoice_index ON invoices (medical_history_id ASC);
